config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  resources :episodes, only: [:index]
  resources :encodes, only: [:index]
  resources :series, only: [:index, :show]
  get '/episodes/:id/encode', to: 'episodes#encode'

  namespace :api do
    namespace :v1 do
      resources :episodes, only: [:index]
      resources :encodes, only: [:update]
      resources :encode_records, only: [:update, :create, :show]
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/encode_record.rb
class EncodeRecord < ApplicationRecord
  belongs_to :episode

  def self.next_encode
    where(finished_at: nil).order(created_at: :asc).limit(1).first
  end
end

app/models/episode.rb
class Episode < ApplicationRecord
  validates_presence_of :episode_file_id
  validates_presence_of :season_number
  validates_presence_of :episode_number
  validates_presence_of :title
  validates_presence_of :air_date
  validates_presence_of :has_file
  validates_presence_of :sonarr_id
  validates_presence_of :path
  validates_presence_of :size
  validates_presence_of :date_added
  validates_presence_of :audio
  validates_presence_of :video
  validates_uniqueness_of :sonarr_id

  belongs_to :series
  has_many :encode_jobs
end

app/models/series.rb
class Series < ApplicationRecord
  validates_presence_of :episode_count
  validates_presence_of :path
  validates_presence_of :season_count
  validates_presence_of :size_on_disk
  validates_presence_of :title
  validates_presence_of :sonarr_id

  validates_uniqueness_of :sonarr_id


  has_many :episodes
end

app/models/worker.rb
class Worker < ApplicationRecord
  require 'securerandom'
  validates_presence_of :location

  def generate_identity
    access_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/api/v1/encode_records_controller.rb
class Api::V1::EncodeRecordsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def create
    EncodeRecord.create(episode_id: params[:format])
  end

  def update
    encode = EncodeRecord.find(params[:id])
    worker = Worker.find_by( access_token: request.headers['IDENTITY'])
    encode.update( finished_at: Time.now,
                   success: true)
    EpisodeUpdater.update(encode.episode)
    EncodeDispatch.dispatch( worker.id )

  end
end

app/controllers/api/v1/episodes_controller.rb
class Api::V1::EpisodesController < ApplicationController
  def index
    render json: Episode.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController

  def index
    @episodes = Episode.all
  end

  def encode
    episode = Episode.find(params[:id])
    EncoderJob.perform_later(episode)
    flash[:notice] = 'Encode Started'
    redirect_to episodes_path
  end
end

app/controllers/series_controller.rb
class SeriesController < ApplicationController
  def index
    @series = Series.all
  end

  def show
    @series = Series.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/encodes/index.html.erb
<% @encodes.each do |encode| %>
  <ul>
    <li>ID:            <%= encode.id %></li>
    <li>Successful:    <%= encode.success %></li>
  </ul>
<% end %>

app/views/episodes/index.html.erb
<h1>All Episodes</h1>

<% @episodes.each do |episode| %>
  <ul>
  <li><%= episode.path %></li>
  <li><%= episode.encoded %></li>
  <li><%= episode.audio %></li>
  <li><%= episode.video %></li>
  <li><%= link_to 'Encode', "/episodes/#{episode.id}/encode" %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Artemis</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
     <% flash.each do |type, message| %>
      <%= content_tag :div, message, class: type %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/series/index.html.erb
<% @series.each do |series|  %>
  <ul>
    <li> <%= series.id %></li>
    <li><%= link_to series.title, series_path(series) %></li>
  </ul>
<% end %>

app/views/series/show.html.erb
<%= @series.title %>
<% @series.episodes.all.each do |episode| %>
  <ul>
    <li><%= episode.title %></li>
    <li><%= episode.encoded %></li>
    <li><%= episode.path %></li>
    <li><%= link_to 'Encode', api_v1_encode_records_path(episode.id), method: :post %></li>
  </ul>
<% end %>